name: PHP Composer

on:
  push:
    branches: [ "Test" ]
  pull_request:
    branches: [ "Test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create A new Project
      run: composer create-project joselfonseca/laravel-api my_laravel_app

    - name: Push directory to another repository
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      uses: cpina/github-action-push-to-another-repository@composite-1.7.1
      with:
        source-directory: my_laravel_app/
        destination-github-username: 'hsnrathore'
        destination-repository-name: 'my_laravel_app'
        user-email: hsnrathore@gmail.com
        target-branch: main
    - name: List the contents
      run: ls -l && cd my_laravel_app && ls -l 
            
    #Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    #Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
